// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace NeoApp.API.Models;

public partial class ControleConsultaContext : DbContext
{
    public ControleConsultaContext()
    {
    }

    public ControleConsultaContext(DbContextOptions<ControleConsultaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Consulta> Consulta { get; set; }

    public virtual DbSet<Medico> Medico { get; set; }

    public virtual DbSet<Paciente> Paciente { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Data Source=(local);Initial Catalog=ControleConsulta;Integrated Security=True;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Consulta>(entity =>
        {
            entity.HasOne(d => d.IdMedicoNavigation).WithMany(p => p.Consulta).HasForeignKey(d => d.IdMedico).HasConstraintName("FK_Consulta_Medico");

            entity.HasOne(d => d.IdPacienteNavigation).WithMany(p => p.Consulta).HasForeignKey(d => d.IdPaciente).HasConstraintName("FK_Consulta_Paciente");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}