// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json; // Importe esta namespace


namespace NeoApp.API.Models;

public partial class Medico
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("nome_medico")]
    [StringLength(50)]
    [Unicode(false)]
    public string NomeMedico { get; set; }

    [Column("password")]
    public string Password { get; set; }

    [InverseProperty("IdMedicoNavigation")]
    [JsonIgnore]
    public virtual ICollection<Consulta> Consulta { get; set; } = new List<Consulta>();
}